CREATE DATABASE IF NOT EXISTS JFDataBase;

USE JFDataBase;

CREATE TABLE IF NOT EXISTS USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER ENUM('EMPLOYER', 'USER') NOT NULL,
    USER_NAME VARCHAR(255) UNIQUE,
    NAME VARCHAR(255),
    AGE INT,
    DESCRIPTION TEXT,
    COMPANY_NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS VACANCIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION TEXT,
    NAME VARCHAR(255),
    USER_NAME VARCHAR(255),
    AGE_FOR_VACANCIES INT,
    FOREIGN KEY (USER_NAME) REFERENCES USERS(USER_NAME)
);